Created models and basic functions for tests
KozielPiotr/shared-bills pull request #1
Opened 2019-12-06 17:31 UTC by KozielPiotr

2019-12-09 21:06 UTC, cmiacz requested changes

2019-12-09 21:06 UTC, cmiacz commented on bills_app/apps.py
>      name = 'bills_app'
Keep names simple. Sufix `_app` is obsolete in case of application. Rename to `bills`

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +class CustomUser(AbstractUser):
Please create separate `Participant` model for billing. It's not needed to mix bill participant with django authentication user model. Do not override default model if not necessary.

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +class Receipt(models.Model):
Keep naming consistent. Rename to `Bill` as the whole project is called `shared_bills` and receipt this is just the bill to share.

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    for_what = models.CharField(max_length=100)
Rename to `title`. Please also consider to add additional `description` field

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    amount = models.DecimalField(max_digits=7, decimal_places=2)
Consider using `MoneyField` from `django-money`
https://github.com/django-money/django-money

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    event = models.ForeignKey(Event, on_delete=models.PROTECT)
Bills should be automatically deleted when the whole event is being removed. Use `on_delete=models.CASCADE`

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    participators = models.ManyToManyField(CustomUser, related_name="participates")
Remove this relation. Model `Participant` should have foreign key to `Event` with backref called `participants` as participants exists only in scope of event and should not be shared between different events.

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    cashier = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.SET_NULL,
Rename to `paymaster`

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    paid_by = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.PROTECT,
Rename to `payer`

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    event = models.ForeignKey(Event, on_delete=models.PROTECT)
`on_delete=models.CASCADE`

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    who_pays = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="paid_cash")
Rename to `issuer`

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    for_who = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="got_cash")
Rename to `acquirer`

2019-12-09 21:06 UTC, cmiacz commented on bills_app/models.py
> +    bought_by = models.ManyToManyField(CustomUser, related_name="bought")
Rename to `participants`

2019-12-09 22:27 UTC, cmiacz commented
Please add migrations to repo

2019-12-10 12:13 UTC, KozielPiotr commented on bills_app/models.py
> +    participators = models.ManyToManyField(CustomUser, related_name="participates")
I'd like to keep this one unchanged. After once created, the participant could be assigned to more than one event.

2019-12-10 19:51 UTC, cmiacz commented on bills_app/models.py
> +    participators = models.ManyToManyField(CustomUser, related_name="participates")
In that case participant should be somehow assigned to user. We don't want to share participant names across all application. As we don't have any authentication schema now, plaese keep participants assigned to events with foreign key

2019-12-10 19:55 UTC, cmiacz commented on bills/models.py
> +    event = models.ForeignKey(Event, on_delete=models.PROTECT)
CASCADE

2019-12-10 19:57 UTC, cmiacz commented on bills/models.py
> +        Participant, on_delete=models.CASCADE, related_name="paid"
PROTECT. Participant cannot be deleted if there are any related payments

2019-12-10 19:59 UTC, cmiacz requested changes

2019-12-10 19:59 UTC, cmiacz commented on bills/models.py
> +        Participant, on_delete=models.CASCADE, related_name="acquired"
PROTECT. Participant cannot be deleted if there are any related payments

2019-12-10 19:59 UTC, cmiacz commented on bills/tests.py
> +    bill.bought_by.add(bought_by)
It seems to be outdated

2019-12-11 20:56 UTC, cmiacz requested changes

2019-12-11 20:56 UTC, cmiacz commented on shared_bills/settings.py
> +SECRET_KEY = "e45i2uj&!e(8#-!_#n6z^vmj+o^dze8g^!jb!n2c4zxif&0r&@"
DO NOT COMMIT SECRET KEY TO REPO
It should be obtained from environment variable

2019-12-11 20:58 UTC, cmiacz approved these changes

2019-12-11 22:11 UTC, merged